$axure.loadCurrentPage({
  "url":"video.html",
  "generationDate":new Date(1400036940370.48),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ede3353f1fc34232a58eddca80b2cad9",
    "type":"Axure:Page",
    "name":"Video",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fa71004551be4b2db90185ed309e76eb",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":20}},
          "adaptiveStyles":{
},
          "masterId":"7eca3fcc01c445f79a990fdeb99a5cab"},
{
          "id":"9acf31d948f34d8c9bb9242aa50c0167",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":110},
            "size":{
              "width":950,
              "height":930},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7e19004a87340c08c3704a9755d3172",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":110},
                "size":{
                  "width":950,
                  "height":930},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/video/u25.png"}},
{
          "id":"230a5a0eeef842ef98aca901abbcc2ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'OpenSans-Semibold', 'Open Sans Semibold', 'Open Sans'",
            "fontWeight":"650",
            "location":{
              "x":525,
              "y":139},
            "size":{
              "width":97,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d81af3abe854d78a822888315ecb061",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'OpenSans-Semibold', 'Open Sans Semibold', 'Open Sans'",
                "fontWeight":"650",
                "location":{
                  "x":525,
                  "y":139},
                "size":{
                  "width":97,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f18e852829124226a782d8ec802348b1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":421,
              "y":185},
            "size":{
              "width":319,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/gallery/u35_line.png"}},
{
          "id":"2b45bafafd4f4a198fd29523daa619b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
            "fontSize":"36px",
            "fontWeight":"700",
            "location":{
              "x":137,
              "y":206},
            "size":{
              "width":900,
              "height":370}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14cbf05f1d2b4d8ca248e937ac948392",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
                "fontSize":"36px",
                "fontWeight":"700",
                "location":{
                  "x":137,
                  "y":206},
                "size":{
                  "width":900,
                  "height":370}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/video/u30.png"}},
{
          "id":"38c4c42408ce4675b650373d1edea34d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
            "fontSize":"36px",
            "fontWeight":"700",
            "location":{
              "x":137,
              "y":610},
            "size":{
              "width":900,
              "height":370}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85af29cbf0694d7e867bf587e14f4b8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
                "fontSize":"36px",
                "fontWeight":"700",
                "location":{
                  "x":137,
                  "y":610},
                "size":{
                  "width":900,
                  "height":370}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/video/u30.png"}},
{
          "id":"a63918d8858c4f2f8466b851bc8eec99",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":1060}},
          "adaptiveStyles":{
},
          "masterId":"8b72bd043b4a4566adb151b8a50c1f55"}]}},
  "masters":{
    "7eca3fcc01c445f79a990fdeb99a5cab":{
      "packageId":"7eca3fcc01c445f79a990fdeb99a5cab",
      "type":"Axure:Master",
      "name":"Navigation#2",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"d96b73e5116343d7a7cead3ca585ff24",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":380,
                "y":0},
              "size":{
                "width":620,
                "height":50},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e675e991c3554e23bb87e8d8f07a67cf",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":380,
                    "y":0},
                  "size":{
                    "width":620,
                    "height":50},
                  "borderWidth":"2",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u5.png"}},
{
            "id":"12243ac1b8de4099938d278e1f17e40d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
              "fontSize":"20px",
              "fontWeight":"200",
              "location":{
                "x":386,
                "y":10},
              "size":{
                "width":111,
                "height":30},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF009933},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dc621ca7d2cf41a894fdb5b2a29bc857",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
                  "fontSize":"20px",
                  "fontWeight":"200",
                  "location":{
                    "x":386,
                    "y":10},
                  "size":{
                    "width":111,
                    "height":30},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF009933},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u7.png"}},
{
            "id":"91551619f67046c88400c5a9b194776b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
              "fontSize":"20px",
              "fontWeight":"200",
              "location":{
                "x":505,
                "y":10},
              "size":{
                "width":111,
                "height":30},
              "borderWidth":"-1",
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"19affa3f6d43477b9bfd2761dcddd3ae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
                  "fontSize":"20px",
                  "fontWeight":"200",
                  "location":{
                    "x":505,
                    "y":10},
                  "size":{
                    "width":111,
                    "height":30},
                  "borderWidth":"-1",
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open About in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"about.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u9.png"}},
{
            "id":"f2a6d3cab7354367999f0e4a4701c391",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
              "fontSize":"20px",
              "fontWeight":"200",
              "location":{
                "x":624,
                "y":10},
              "size":{
                "width":111,
                "height":30},
              "borderWidth":"-1",
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8375330ccaab4868ac01adeac3998c7b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
                  "fontSize":"20px",
                  "fontWeight":"200",
                  "location":{
                    "x":624,
                    "y":10},
                  "size":{
                    "width":111,
                    "height":30},
                  "borderWidth":"-1",
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Events in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"events.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u9.png"}},
{
            "id":"ecd472da246a4b0ebde176f8cf654db0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
              "fontSize":"20px",
              "fontWeight":"200",
              "location":{
                "x":745,
                "y":10},
              "size":{
                "width":111,
                "height":30},
              "borderWidth":"-1",
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7324f80ca2fe4e32ac07761ad6e447ed",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
                  "fontSize":"20px",
                  "fontWeight":"200",
                  "location":{
                    "x":745,
                    "y":10},
                  "size":{
                    "width":111,
                    "height":30},
                  "borderWidth":"-1",
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show MediaFlyout treat as flyout",
                        "objectsToFades":[{
                            "objectPath":["e667355ff9d3481087a63a2969446b1f"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"flyout"}}}]}]}]}},
            "images":{
              "normal~":"images/home/u9.png"}},
{
            "id":"748b192633a9422ea3d447d9511e8dee",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
              "fontSize":"20px",
              "fontWeight":"200",
              "location":{
                "x":867,
                "y":10},
              "size":{
                "width":111,
                "height":30},
              "borderWidth":"-1",
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2f01050f65424488a5b2a138706ce60e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
                  "fontSize":"20px",
                  "fontWeight":"200",
                  "location":{
                    "x":867,
                    "y":10},
                  "size":{
                    "width":111,
                    "height":30},
                  "borderWidth":"-1",
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Contact in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contact.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u9.png"}},
{
            "id":"e667355ff9d3481087a63a2969446b1f",
            "label":"MediaFlyout",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":739,
                "y":50},
              "size":{
                "width":160,
                "height":114},
              "visible":false},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"3dca0436bbfd4ad8b4c6dfb5ad56df4b",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"390cf107ac7d47c6bc44886f986313e5",
                    "label":"",
                    "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC},
                      "size":{
                        "width":160,
                        "height":114},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFAEAEAE}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"f8d846addf9d44219093509b900f40b3",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC},
                          "size":{
                            "width":160,
                            "height":114},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFAEAEAE}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/u18.png"}},
{
                    "id":"3a6132e387424d6fbbf2248b3654016c",
                    "label":"",
                    "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC},
                      "location":{
                        "x":14,
                        "y":11},
                      "size":{
                        "width":138,
                        "height":20},
                      "borderWidth":"-1",
                      "cornerRadiusTopLeft":"5"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"aba5fdd5f99240e3ab65e051386a96c5",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC},
                          "location":{
                            "x":14,
                            "y":11},
                          "size":{
                            "width":138,
                            "height":20},
                          "borderWidth":"-1",
                          "cornerRadiusTopLeft":"5"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Gallery in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"gallery.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u20.png"}},
{
                    "id":"6889745b526b4678a3382c3ecc3ca560",
                    "label":"",
                    "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC},
                      "location":{
                        "x":14,
                        "y":48},
                      "size":{
                        "width":138,
                        "height":20},
                      "borderWidth":"-1",
                      "cornerRadiusTopLeft":"5"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2bdce835ad7341c099f582ef7f5739a7",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC},
                          "location":{
                            "x":14,
                            "y":48},
                          "size":{
                            "width":138,
                            "height":20},
                          "borderWidth":"-1",
                          "cornerRadiusTopLeft":"5"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Music in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"music.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u20.png"}},
{
                    "id":"604d913d8219424b904ea3538c9e709d",
                    "label":"",
                    "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC},
                      "location":{
                        "x":14,
                        "y":83},
                      "size":{
                        "width":138,
                        "height":20},
                      "borderWidth":"-1",
                      "cornerRadiusTopLeft":"5"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0ab12be8507b4b5d96523b9689bef6d8",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC},
                          "location":{
                            "x":14,
                            "y":83},
                          "size":{
                            "width":138,
                            "height":20},
                          "borderWidth":"-1",
                          "cornerRadiusTopLeft":"5"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Video in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"video.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u20.png"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]},
{
            "id":"5a09e75d78154126b36e9e911c560920",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":54,
                "y":0},
              "size":{
                "width":280,
                "height":42}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bb7b3553b986493d94efa8d3936ba89e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":54,
                    "y":0},
                  "size":{
                    "width":280,
                    "height":42}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u26.png"}},
{
            "id":"a14ef670f2004442bc29daa99eee55ba",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":50,
                "y":54},
              "size":{
                "width":950,
                "height":10},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF999999}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/home/u28_line.png"}}]}},
    "8b72bd043b4a4566adb151b8a50c1f55":{
      "packageId":"8b72bd043b4a4566adb151b8a50c1f55",
      "type":"Axure:Master",
      "name":"Footer",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"20f3cd74ae3948eb9611ff6704f923e8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
              "fontWeight":"700",
              "fill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "location":{
                "x":-100,
                "y":0},
              "size":{
                "width":950,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"21b4e9ebc28c473dab39ebcb625bdf01",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
                  "fontWeight":"700",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "location":{
                    "x":-100,
                    "y":0},
                  "size":{
                    "width":950,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u71.png"}}]}}},
  "objectPaths":{
    "fa71004551be4b2db90185ed309e76eb":{
      "scriptId":"u0",
      "d96b73e5116343d7a7cead3ca585ff24":{
        "scriptId":"u1"},
      "e675e991c3554e23bb87e8d8f07a67cf":{
        "scriptId":"u2"},
      "12243ac1b8de4099938d278e1f17e40d":{
        "scriptId":"u3"},
      "dc621ca7d2cf41a894fdb5b2a29bc857":{
        "scriptId":"u4"},
      "91551619f67046c88400c5a9b194776b":{
        "scriptId":"u5"},
      "19affa3f6d43477b9bfd2761dcddd3ae":{
        "scriptId":"u6"},
      "f2a6d3cab7354367999f0e4a4701c391":{
        "scriptId":"u7"},
      "8375330ccaab4868ac01adeac3998c7b":{
        "scriptId":"u8"},
      "ecd472da246a4b0ebde176f8cf654db0":{
        "scriptId":"u9"},
      "7324f80ca2fe4e32ac07761ad6e447ed":{
        "scriptId":"u10"},
      "748b192633a9422ea3d447d9511e8dee":{
        "scriptId":"u11"},
      "2f01050f65424488a5b2a138706ce60e":{
        "scriptId":"u12"},
      "e667355ff9d3481087a63a2969446b1f":{
        "scriptId":"u13"},
      "390cf107ac7d47c6bc44886f986313e5":{
        "scriptId":"u14"},
      "f8d846addf9d44219093509b900f40b3":{
        "scriptId":"u15"},
      "3a6132e387424d6fbbf2248b3654016c":{
        "scriptId":"u16"},
      "aba5fdd5f99240e3ab65e051386a96c5":{
        "scriptId":"u17"},
      "6889745b526b4678a3382c3ecc3ca560":{
        "scriptId":"u18"},
      "2bdce835ad7341c099f582ef7f5739a7":{
        "scriptId":"u19"},
      "604d913d8219424b904ea3538c9e709d":{
        "scriptId":"u20"},
      "0ab12be8507b4b5d96523b9689bef6d8":{
        "scriptId":"u21"},
      "5a09e75d78154126b36e9e911c560920":{
        "scriptId":"u22"},
      "bb7b3553b986493d94efa8d3936ba89e":{
        "scriptId":"u23"},
      "a14ef670f2004442bc29daa99eee55ba":{
        "scriptId":"u24"}},
    "9acf31d948f34d8c9bb9242aa50c0167":{
      "scriptId":"u25"},
    "e7e19004a87340c08c3704a9755d3172":{
      "scriptId":"u26"},
    "230a5a0eeef842ef98aca901abbcc2ed":{
      "scriptId":"u27"},
    "8d81af3abe854d78a822888315ecb061":{
      "scriptId":"u28"},
    "f18e852829124226a782d8ec802348b1":{
      "scriptId":"u29"},
    "2b45bafafd4f4a198fd29523daa619b8":{
      "scriptId":"u30"},
    "14cbf05f1d2b4d8ca248e937ac948392":{
      "scriptId":"u31"},
    "38c4c42408ce4675b650373d1edea34d":{
      "scriptId":"u32"},
    "85af29cbf0694d7e867bf587e14f4b8e":{
      "scriptId":"u33"},
    "a63918d8858c4f2f8466b851bc8eec99":{
      "scriptId":"u34",
      "20f3cd74ae3948eb9611ff6704f923e8":{
        "scriptId":"u35"},
      "21b4e9ebc28c473dab39ebcb625bdf01":{
        "scriptId":"u36"}}}});