$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1400738114988.07),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e1bfcd553fbe40efb1eabd9340739635",
    "type":"Axure:Page",
    "name":"HOME",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3025bd8a1db94dbb90a663f8a1af4cbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF3F3F3},
            "location":{
              "x":-7,
              "y":892},
            "size":{
              "width":1247,
              "height":678},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20515a9216d24a20b76a637fe5d9ef47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF3F3F3},
                "location":{
                  "x":-7,
                  "y":892},
                "size":{
                  "width":1247,
                  "height":678},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"ab7c937bd1e7406f9c9e58fbd36086a1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":2,
              "y":0},
            "size":{
              "width":1238,
              "height":894}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f362abb5c94645839e8fc6dfa132ee87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2,
                  "y":0},
                "size":{
                  "width":1238,
                  "height":894}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.jpg"}},
{
          "id":"8b1d143f3d974c529c370143ed0af0ba",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":-4}},
          "adaptiveStyles":{
},
          "masterId":"f0b49f2f4fa94337b1505ee98ea00ada"},
{
          "id":"9fa67eff707e4b1aba8ba19d1d63330c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":575},
            "size":{
              "width":730,
              "height":260},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02e07adbd54249e692c0d5e65a12ee4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":575},
                "size":{
                  "width":730,
                  "height":260},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u34.png"}},
{
          "id":"d20052d52cd64f1ebf91817ccffde675",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1569}},
          "adaptiveStyles":{
},
          "masterId":"01fcc325c530467984fe7b5b2ffa3547"},
{
          "id":"9f3ab578429a48e786b5442c406c036d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":303,
              "y":602},
            "size":{
              "width":700,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"832ac8f833c24981b17a0e107405f241",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":303,
                  "y":602},
                "size":{
                  "width":700,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bba97e4a502044eebb3ddd995405f1be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
            "fontSize":"14px",
            "fontWeight":"200",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":575,
              "y":794},
            "size":{
              "width":110,
              "height":30},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f0453a27a0940fca1e47e2cc220f7cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
                "fontSize":"14px",
                "fontWeight":"200",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":575,
                  "y":794},
                "size":{
                  "width":110,
                  "height":30},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u53.png"}},
{
          "id":"502b29fc5cb145a5979888b504fb0e1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":303,
              "y":682},
            "size":{
              "width":670,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1b12ea482ea4b8a813fb37528cae136",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":303,
                  "y":682},
                "size":{
                  "width":670,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u55.png"}},
{
          "id":"5dc96e84c7bc40a5900ed74eeb210ee3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":303,
              "y":722},
            "size":{
              "width":670,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6484d94f79a84d8fb24d2ddb0b263b6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":303,
                  "y":722},
                "size":{
                  "width":670,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u55.png"}},
{
          "id":"c45fe5a6643c4d4188f445c647b3eba2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":303,
              "y":702},
            "size":{
              "width":620,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d895324d9524f5baebdec6203d88136",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":303,
                  "y":702},
                "size":{
                  "width":620,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u59.png"}},
{
          "id":"d1cf08c7a94b497f815417a80ef5664b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":303,
              "y":742},
            "size":{
              "width":650,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d425257089c848e6a0e521a5058ae360",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":303,
                  "y":742},
                "size":{
                  "width":650,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u61.png"}},
{
          "id":"5780ad6f196b48ceaf2d2f14380e6592",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":303,
              "y":762},
            "size":{
              "width":670,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9665dc3834540f092c84af2920b71a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":303,
                  "y":762},
                "size":{
                  "width":670,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u55.png"}},
{
          "id":"1568df6a36504e8ca3dda279290bdc2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":940},
            "size":{
              "width":550,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"993776c06a344ab7a1294f8b1d0069ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":940},
                "size":{
                  "width":550,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d7764fbde2747e9a1c1fe735b8ebb29",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":629,
              "y":960},
            "size":{
              "width":10,
              "height":550},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE2E2E1}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u67_line.png"}},
{
          "id":"ba20358607164b39804d7baea629cc00",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":675,
              "y":1040},
            "size":{
              "width":533,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f42739a5fcb44d79ade5c3febffd6a42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":675,
                  "y":1040},
                "size":{
                  "width":533,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u68.png"}},
{
          "id":"0601648e39c8486fa5d4347719d12d9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":675,
              "y":1080},
            "size":{
              "width":533,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fa9b7a47cef40519a53d401fd30383f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":675,
                  "y":1080},
                "size":{
                  "width":533,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u68.png"}},
{
          "id":"cabb439e59ae4c4497d7641e169dc5a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":675,
              "y":1060},
            "size":{
              "width":494,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df2ca425fba74f5fafb4850eadb2d4b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":675,
                  "y":1060},
                "size":{
                  "width":494,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u72.png"}},
{
          "id":"029c30f7355344edbf641e5d572ed00f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":675,
              "y":1100},
            "size":{
              "width":517,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20daaa7c514a4c9cbad83d4c1c1f3951",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":675,
                  "y":1100},
                "size":{
                  "width":517,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u74.png"}},
{
          "id":"3c451bb4813f4f1ebb836d91da69c842",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":675,
              "y":1120},
            "size":{
              "width":533,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9619d56e1e5d4941ab2583167138a5be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":675,
                  "y":1120},
                "size":{
                  "width":533,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u68.png"}},
{
          "id":"19ce71a8f6d24b66b3761c877c34cc83",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":1176},
            "size":{
              "width":518,
              "height":210}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe33fed3351544f1a6de58e717f9561e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":1176},
                "size":{
                  "width":518,
                  "height":210}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u78.png"}},
{
          "id":"c57357d86a5d4c77adbdbb7432b49a5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
            "fontSize":"14px",
            "fontWeight":"200",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":257,
              "y":1450},
            "size":{
              "width":110,
              "height":30},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0dc899f4d3064e5eb7c833daf6ac52c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
                "fontSize":"14px",
                "fontWeight":"200",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":257,
                  "y":1450},
                "size":{
                  "width":110,
                  "height":30},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u53.png"}},
{
          "id":"2292f46511c14c6cb5db3f2ad601a214",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":675,
              "y":941},
            "size":{
              "width":550,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc7e7f121d3d4d78bcd21c27a1c436fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":675,
                  "y":941},
                "size":{
                  "width":550,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6282e97aae04d879cf0130b7b9db9b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Lato-Bold', 'Lato Bold', 'Lato'",
            "fontSize":"20px",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":690,
              "y":1162},
            "size":{
              "width":496,
              "height":224}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"487a24d28e6a41da9cb5ed17c1b699ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Lato-Bold', 'Lato Bold', 'Lato'",
                "fontSize":"20px",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":690,
                  "y":1162},
                "size":{
                  "width":496,
                  "height":224}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u84.png"}},
{
          "id":"0ae974be288347dd89b4e9ed9da321b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
            "fontSize":"14px",
            "fontWeight":"200",
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":887,
              "y":1450},
            "size":{
              "width":110,
              "height":30},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40522224502f4c4f8eedc2ad847d7782",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
                "fontSize":"14px",
                "fontWeight":"200",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":887,
                  "y":1450},
                "size":{
                  "width":110,
                  "height":30},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u53.png"}},
{
          "id":"fec66b5c41e6405197b069629b902e51",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":48,
              "y":1050},
            "size":{
              "width":539,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f1e5ee6261d4c5e81c9f4d14f3b9f4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":48,
                  "y":1050},
                "size":{
                  "width":539,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u88.png"}},
{
          "id":"99e2d1c3c96a45e0a915a068b651fe47",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":48,
              "y":1090},
            "size":{
              "width":539,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fbdff61870748ffa2ec0f851b866692",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":48,
                  "y":1090},
                "size":{
                  "width":539,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u88.png"}},
{
          "id":"5ef561c470e14da2abf3cd4ab1a32923",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":48,
              "y":1070},
            "size":{
              "width":498,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1893c91af1fb41ada800a479dbc4e40e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":48,
                  "y":1070},
                "size":{
                  "width":498,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u92.png"}},
{
          "id":"74a72ab2910c49f095b3bd5803e3eccc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":48,
              "y":1110},
            "size":{
              "width":523,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7462b9486e945608e5f3c0de34de225",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":48,
                  "y":1110},
                "size":{
                  "width":523,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u94.png"}},
{
          "id":"28dca5c155884a9f8b3fe499c2688df7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":48,
              "y":1130},
            "size":{
              "width":539,
              "height":10},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3239c70c77442d693fbac17a0554c10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":48,
                  "y":1130},
                "size":{
                  "width":539,
                  "height":10},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u88.png"}}]}},
  "masters":{
    "f0b49f2f4fa94337b1505ee98ea00ada":{
      "packageId":"f0b49f2f4fa94337b1505ee98ea00ada",
      "type":"Axure:Master",
      "name":"Navigation",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"413ec060cbe043699d39ed6c7eab701e",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":336,
                "y":14},
              "size":{
                "width":557,
                "height":71}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"163d51fd01c147a29edd0bdc3f757025",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":336,
                    "y":14},
                  "size":{
                    "width":557,
                    "height":71}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open HOME in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u5.png"}},
{
            "id":"120e78f7b79745f0be8db5ec4ff5a08d",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":380,
                "y":114},
              "size":{
                "width":500,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF009966}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/home/u7_line.png"}},
{
            "id":"f6f5be4ded154d0ea3246b28d4790b3d",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
              "fontSize":"16px",
              "fontWeight":"200",
              "location":{
                "x":438,
                "y":94},
              "size":{
                "width":55,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"72d6b005b39d4078a18c4b5f7f1524c3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
                  "fontSize":"16px",
                  "fontWeight":"200",
                  "location":{
                    "x":438,
                    "y":94},
                  "size":{
                    "width":55,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open ABOUT in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"about.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"980fd7671da44dd2825f46aa300e1bf5",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
              "fontSize":"16px",
              "fontWeight":"200",
              "location":{
                "x":548,
                "y":94},
              "size":{
                "width":52,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"68a7befc57ae4b3cb2cbee04fa7a96b1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
                  "fontSize":"16px",
                  "fontWeight":"200",
                  "location":{
                    "x":548,
                    "y":94},
                  "size":{
                    "width":52,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show DropDown treat as flyout",
                        "objectsToFades":[{
                            "objectPath":["1720fa68d4ad42e088a05ce94ff3401b"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"flyout"}}}]}]}]}},
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"910a18bc95674775ab4ed2e9816a3cf5",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
              "fontSize":"16px",
              "fontWeight":"200",
              "location":{
                "x":654,
                "y":94},
              "size":{
                "width":58,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"760a27a002c64e90983493184881105b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
                  "fontSize":"16px",
                  "fontWeight":"200",
                  "location":{
                    "x":654,
                    "y":94},
                  "size":{
                    "width":58,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open EVENTS in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"events.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"076183ea48f54737b6d32cfa9c27859e",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
              "fontSize":"16px",
              "fontWeight":"200",
              "location":{
                "x":766,
                "y":94},
              "size":{
                "width":76,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0e624b0357ca437f8a5f9de79c679475",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
                  "fontSize":"16px",
                  "fontWeight":"200",
                  "location":{
                    "x":766,
                    "y":94},
                  "size":{
                    "width":76,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open CONTACT in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contact.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1720fa68d4ad42e088a05ce94ff3401b",
            "label":"DropDown",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":512,
                "y":131},
              "size":{
                "width":140,
                "height":154},
              "visible":false},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"d84aad9dd3464e63bec2bca8b06ea7df",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"29ed1cef03e94257a1e53c985deb6057",
                    "label":"",
                    "parentDynamicPanel":"1720fa68d4ad42e088a05ce94ff3401b",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC},
                      "size":{
                        "width":140,
                        "height":154},
                      "borderWidth":"3",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFF666666}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d25dcc43705c4f04880679ed359293d1",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"1720fa68d4ad42e088a05ce94ff3401b",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC},
                          "size":{
                            "width":140,
                            "height":154},
                          "borderWidth":"3",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFF666666}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/u17.png"}},
{
                    "id":"174b0fa6685545eb9e09b897bd773d30",
                    "label":"",
                    "parentDynamicPanel":"1720fa68d4ad42e088a05ce94ff3401b",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h2",
                    "visible":true,
                    "style":{
                      "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
                      "fontWeight":"200",
                      "location":{
                        "x":28,
                        "y":16},
                      "size":{
                        "width":103,
                        "height":29}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"5e09372979c9401481aba5c272a5346d",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"1720fa68d4ad42e088a05ce94ff3401b",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
                          "fontWeight":"200",
                          "location":{
                            "x":28,
                            "y":16},
                          "size":{
                            "width":103,
                            "height":29}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Gallery in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"gallery.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"ffdf3cc60bb2427f81fc28ca8c0d9fb2",
                    "label":"",
                    "parentDynamicPanel":"1720fa68d4ad42e088a05ce94ff3401b",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h2",
                    "visible":true,
                    "style":{
                      "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
                      "fontWeight":"200",
                      "location":{
                        "x":40,
                        "y":62},
                      "size":{
                        "width":77,
                        "height":29}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"02a3ab6f23a34c188b669c8516be220b",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"1720fa68d4ad42e088a05ce94ff3401b",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
                          "fontWeight":"200",
                          "location":{
                            "x":40,
                            "y":62},
                          "size":{
                            "width":77,
                            "height":29}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Music in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"music.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"b2c8a60cce474411871b072ba51f7c16",
                    "label":"",
                    "parentDynamicPanel":"1720fa68d4ad42e088a05ce94ff3401b",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h2",
                    "visible":true,
                    "style":{
                      "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
                      "fontWeight":"200",
                      "location":{
                        "x":35,
                        "y":106},
                      "size":{
                        "width":88,
                        "height":29}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"a97e7dba52564050b9b821ef5eaac77a",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"1720fa68d4ad42e088a05ce94ff3401b",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
                          "fontWeight":"200",
                          "location":{
                            "x":35,
                            "y":106},
                          "size":{
                            "width":88,
                            "height":29}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Video in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"video.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"4a7cee848f834c9788f765aac7daeb9a",
                    "label":"",
                    "parentDynamicPanel":"1720fa68d4ad42e088a05ce94ff3401b",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":140,
                        "height":154},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFF666666}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2b03e388d8db4e418673d5328f30aa08",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"1720fa68d4ad42e088a05ce94ff3401b",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":140,
                            "height":154},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFF666666}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/u25.png"}},
{
                    "id":"46395910a844454db596570509146020",
                    "label":"",
                    "parentDynamicPanel":"1720fa68d4ad42e088a05ce94ff3401b",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h2",
                    "visible":true,
                    "style":{
                      "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
                      "fontSize":"16px",
                      "fontWeight":"200",
                      "location":{
                        "x":33,
                        "y":20},
                      "size":{
                        "width":68,
                        "height":19}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"a6473152e80c417e87f3f4577fb0db8d",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"1720fa68d4ad42e088a05ce94ff3401b",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
                          "fontSize":"16px",
                          "fontWeight":"200",
                          "location":{
                            "x":33,
                            "y":20},
                          "size":{
                            "width":68,
                            "height":19}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Gallery in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"gallery.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"1db55589841c4d53826a2cab5678a125",
                    "label":"",
                    "parentDynamicPanel":"1720fa68d4ad42e088a05ce94ff3401b",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h2",
                    "visible":true,
                    "style":{
                      "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
                      "fontSize":"16px",
                      "fontWeight":"200",
                      "location":{
                        "x":43,
                        "y":61},
                      "size":{
                        "width":52,
                        "height":19}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2480c51abe1c4d7cb82d83359d78d14c",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"1720fa68d4ad42e088a05ce94ff3401b",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
                          "fontSize":"16px",
                          "fontWeight":"200",
                          "location":{
                            "x":43,
                            "y":61},
                          "size":{
                            "width":52,
                            "height":19}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Music in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"music.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"459883cdc0a345a38bb5be01086bb563",
                    "label":"",
                    "parentDynamicPanel":"1720fa68d4ad42e088a05ce94ff3401b",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"h2",
                    "visible":true,
                    "style":{
                      "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
                      "fontSize":"16px",
                      "fontWeight":"200",
                      "location":{
                        "x":39,
                        "y":101},
                      "size":{
                        "width":58,
                        "height":19}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"78e6e2fca8fc494a8f8857e56f5dff51",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"1720fa68d4ad42e088a05ce94ff3401b",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
                          "fontSize":"16px",
                          "fontWeight":"200",
                          "location":{
                            "x":39,
                            "y":101},
                          "size":{
                            "width":58,
                            "height":19}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Video in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"video.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]},
{
            "id":"da5c11053f0c4fdd80518aa366b196df",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":-4},
              "size":{
                "width":1230,
                "height":10},
              "borderWidth":"3",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF009966}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/home/u33_line.png"}}]}},
    "01fcc325c530467984fe7b5b2ffa3547":{
      "packageId":"01fcc325c530467984fe7b5b2ffa3547",
      "type":"Axure:Master",
      "name":"Footer",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"41ef3bbaf98d4cada02ed06d2f1ade2b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF45494E},
              "location":{
                "x":10.0000610351563,
                "y":0},
              "size":{
                "width":1240,
                "height":40},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"87503be58c5d4824997e6a25026ee01b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF45494E},
                  "location":{
                    "x":10.0000610351563,
                    "y":0},
                  "size":{
                    "width":1240,
                    "height":40},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u37.png"}},
{
            "id":"0759cbc86b3346c6861ecebf18064bd8",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
              "fontSize":"16px",
              "fontWeight":"200",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC,
                "opacity":1},
              "location":{
                "x":155.999969482422,
                "y":10},
              "size":{
                "width":55,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"001ff471e4a446e3b9fc362151ffe608",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
                  "fontSize":"16px",
                  "fontWeight":"200",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC,
                    "opacity":1},
                  "location":{
                    "x":155.999969482422,
                    "y":10},
                  "size":{
                    "width":55,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open ABOUT in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"about.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f53d4424bfdb4c26a8259c052b0cc861",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
              "fontSize":"16px",
              "fontWeight":"200",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC,
                "opacity":1},
              "location":{
                "x":265.999969482422,
                "y":10},
              "size":{
                "width":52,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9b769ca78067462793da96bd147858b4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
                  "fontSize":"16px",
                  "fontWeight":"200",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC,
                    "opacity":1},
                  "location":{
                    "x":265.999969482422,
                    "y":10},
                  "size":{
                    "width":52,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show/Hide Widget",
                        "objectsToFades":[]}]}]}},
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2be18e679a5f453690f4a43882db3413",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
              "fontSize":"16px",
              "fontWeight":"200",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC,
                "opacity":1},
              "location":{
                "x":371.999969482422,
                "y":10},
              "size":{
                "width":58,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"412ea9118ecc44ca877779fd940cd980",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
                  "fontSize":"16px",
                  "fontWeight":"200",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC,
                    "opacity":1},
                  "location":{
                    "x":371.999969482422,
                    "y":10},
                  "size":{
                    "width":58,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open EVENTS in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"events.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ad6a74e4108f4986b6b5d75f258d7497",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
              "fontSize":"16px",
              "fontWeight":"200",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC,
                "opacity":1},
              "location":{
                "x":483.999969482422,
                "y":10},
              "size":{
                "width":76,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4620515b305041beaa18ee93f03ef621",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
                  "fontSize":"16px",
                  "fontWeight":"200",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC,
                    "opacity":1},
                  "location":{
                    "x":483.999969482422,
                    "y":10},
                  "size":{
                    "width":76,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open CONTACT in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contact.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9c9923c62a4e46febcdc252ed664beb6",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
              "fontSize":"16px",
              "fontWeight":"200",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC,
                "opacity":1},
              "location":{
                "x":54.9999694824219,
                "y":10},
              "size":{
                "width":50,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"816b3c0e46bc4fed873744e829a628ca",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
                  "fontSize":"16px",
                  "fontWeight":"200",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC,
                    "opacity":1},
                  "location":{
                    "x":54.9999694824219,
                    "y":10},
                  "size":{
                    "width":50,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open HOME in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"d0b0d3d9b08a4181bce457b79e660d24",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
              "fontSize":"16px",
              "fontWeight":"200",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC,
                "opacity":1},
              "location":{
                "x":994,
                "y":10},
              "size":{
                "width":241,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"24e0b73a476949739dff6e3564be539b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Lato-Light', 'Lato Light', 'Lato'",
                  "fontSize":"16px",
                  "fontWeight":"200",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC,
                    "opacity":1},
                  "location":{
                    "x":994,
                    "y":10},
                  "size":{
                    "width":241,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "3025bd8a1db94dbb90a663f8a1af4cbe":{
      "scriptId":"u0"},
    "20515a9216d24a20b76a637fe5d9ef47":{
      "scriptId":"u1"},
    "ab7c937bd1e7406f9c9e58fbd36086a1":{
      "scriptId":"u2"},
    "f362abb5c94645839e8fc6dfa132ee87":{
      "scriptId":"u3"},
    "8b1d143f3d974c529c370143ed0af0ba":{
      "scriptId":"u4",
      "413ec060cbe043699d39ed6c7eab701e":{
        "scriptId":"u5"},
      "163d51fd01c147a29edd0bdc3f757025":{
        "scriptId":"u6"},
      "120e78f7b79745f0be8db5ec4ff5a08d":{
        "scriptId":"u7"},
      "f6f5be4ded154d0ea3246b28d4790b3d":{
        "scriptId":"u8"},
      "72d6b005b39d4078a18c4b5f7f1524c3":{
        "scriptId":"u9"},
      "980fd7671da44dd2825f46aa300e1bf5":{
        "scriptId":"u10"},
      "68a7befc57ae4b3cb2cbee04fa7a96b1":{
        "scriptId":"u11"},
      "910a18bc95674775ab4ed2e9816a3cf5":{
        "scriptId":"u12"},
      "760a27a002c64e90983493184881105b":{
        "scriptId":"u13"},
      "076183ea48f54737b6d32cfa9c27859e":{
        "scriptId":"u14"},
      "0e624b0357ca437f8a5f9de79c679475":{
        "scriptId":"u15"},
      "1720fa68d4ad42e088a05ce94ff3401b":{
        "scriptId":"u16"},
      "29ed1cef03e94257a1e53c985deb6057":{
        "scriptId":"u17"},
      "d25dcc43705c4f04880679ed359293d1":{
        "scriptId":"u18"},
      "174b0fa6685545eb9e09b897bd773d30":{
        "scriptId":"u19"},
      "5e09372979c9401481aba5c272a5346d":{
        "scriptId":"u20"},
      "ffdf3cc60bb2427f81fc28ca8c0d9fb2":{
        "scriptId":"u21"},
      "02a3ab6f23a34c188b669c8516be220b":{
        "scriptId":"u22"},
      "b2c8a60cce474411871b072ba51f7c16":{
        "scriptId":"u23"},
      "a97e7dba52564050b9b821ef5eaac77a":{
        "scriptId":"u24"},
      "4a7cee848f834c9788f765aac7daeb9a":{
        "scriptId":"u25"},
      "2b03e388d8db4e418673d5328f30aa08":{
        "scriptId":"u26"},
      "46395910a844454db596570509146020":{
        "scriptId":"u27"},
      "a6473152e80c417e87f3f4577fb0db8d":{
        "scriptId":"u28"},
      "1db55589841c4d53826a2cab5678a125":{
        "scriptId":"u29"},
      "2480c51abe1c4d7cb82d83359d78d14c":{
        "scriptId":"u30"},
      "459883cdc0a345a38bb5be01086bb563":{
        "scriptId":"u31"},
      "78e6e2fca8fc494a8f8857e56f5dff51":{
        "scriptId":"u32"},
      "da5c11053f0c4fdd80518aa366b196df":{
        "scriptId":"u33"}},
    "9fa67eff707e4b1aba8ba19d1d63330c":{
      "scriptId":"u34"},
    "02e07adbd54249e692c0d5e65a12ee4a":{
      "scriptId":"u35"},
    "d20052d52cd64f1ebf91817ccffde675":{
      "scriptId":"u36",
      "41ef3bbaf98d4cada02ed06d2f1ade2b":{
        "scriptId":"u37"},
      "87503be58c5d4824997e6a25026ee01b":{
        "scriptId":"u38"},
      "0759cbc86b3346c6861ecebf18064bd8":{
        "scriptId":"u39"},
      "001ff471e4a446e3b9fc362151ffe608":{
        "scriptId":"u40"},
      "f53d4424bfdb4c26a8259c052b0cc861":{
        "scriptId":"u41"},
      "9b769ca78067462793da96bd147858b4":{
        "scriptId":"u42"},
      "2be18e679a5f453690f4a43882db3413":{
        "scriptId":"u43"},
      "412ea9118ecc44ca877779fd940cd980":{
        "scriptId":"u44"},
      "ad6a74e4108f4986b6b5d75f258d7497":{
        "scriptId":"u45"},
      "4620515b305041beaa18ee93f03ef621":{
        "scriptId":"u46"},
      "9c9923c62a4e46febcdc252ed664beb6":{
        "scriptId":"u47"},
      "816b3c0e46bc4fed873744e829a628ca":{
        "scriptId":"u48"},
      "d0b0d3d9b08a4181bce457b79e660d24":{
        "scriptId":"u49"},
      "24e0b73a476949739dff6e3564be539b":{
        "scriptId":"u50"}},
    "9f3ab578429a48e786b5442c406c036d":{
      "scriptId":"u51"},
    "832ac8f833c24981b17a0e107405f241":{
      "scriptId":"u52"},
    "bba97e4a502044eebb3ddd995405f1be":{
      "scriptId":"u53"},
    "9f0453a27a0940fca1e47e2cc220f7cb":{
      "scriptId":"u54"},
    "502b29fc5cb145a5979888b504fb0e1c":{
      "scriptId":"u55"},
    "b1b12ea482ea4b8a813fb37528cae136":{
      "scriptId":"u56"},
    "5dc96e84c7bc40a5900ed74eeb210ee3":{
      "scriptId":"u57"},
    "6484d94f79a84d8fb24d2ddb0b263b6d":{
      "scriptId":"u58"},
    "c45fe5a6643c4d4188f445c647b3eba2":{
      "scriptId":"u59"},
    "8d895324d9524f5baebdec6203d88136":{
      "scriptId":"u60"},
    "d1cf08c7a94b497f815417a80ef5664b":{
      "scriptId":"u61"},
    "d425257089c848e6a0e521a5058ae360":{
      "scriptId":"u62"},
    "5780ad6f196b48ceaf2d2f14380e6592":{
      "scriptId":"u63"},
    "f9665dc3834540f092c84af2920b71a1":{
      "scriptId":"u64"},
    "1568df6a36504e8ca3dda279290bdc2c":{
      "scriptId":"u65"},
    "993776c06a344ab7a1294f8b1d0069ce":{
      "scriptId":"u66"},
    "5d7764fbde2747e9a1c1fe735b8ebb29":{
      "scriptId":"u67"},
    "ba20358607164b39804d7baea629cc00":{
      "scriptId":"u68"},
    "f42739a5fcb44d79ade5c3febffd6a42":{
      "scriptId":"u69"},
    "0601648e39c8486fa5d4347719d12d9a":{
      "scriptId":"u70"},
    "2fa9b7a47cef40519a53d401fd30383f":{
      "scriptId":"u71"},
    "cabb439e59ae4c4497d7641e169dc5a2":{
      "scriptId":"u72"},
    "df2ca425fba74f5fafb4850eadb2d4b9":{
      "scriptId":"u73"},
    "029c30f7355344edbf641e5d572ed00f":{
      "scriptId":"u74"},
    "20daaa7c514a4c9cbad83d4c1c1f3951":{
      "scriptId":"u75"},
    "3c451bb4813f4f1ebb836d91da69c842":{
      "scriptId":"u76"},
    "9619d56e1e5d4941ab2583167138a5be":{
      "scriptId":"u77"},
    "19ce71a8f6d24b66b3761c877c34cc83":{
      "scriptId":"u78"},
    "fe33fed3351544f1a6de58e717f9561e":{
      "scriptId":"u79"},
    "c57357d86a5d4c77adbdbb7432b49a5d":{
      "scriptId":"u80"},
    "0dc899f4d3064e5eb7c833daf6ac52c4":{
      "scriptId":"u81"},
    "2292f46511c14c6cb5db3f2ad601a214":{
      "scriptId":"u82"},
    "cc7e7f121d3d4d78bcd21c27a1c436fa":{
      "scriptId":"u83"},
    "a6282e97aae04d879cf0130b7b9db9b7":{
      "scriptId":"u84"},
    "487a24d28e6a41da9cb5ed17c1b699ed":{
      "scriptId":"u85"},
    "0ae974be288347dd89b4e9ed9da321b3":{
      "scriptId":"u86"},
    "40522224502f4c4f8eedc2ad847d7782":{
      "scriptId":"u87"},
    "fec66b5c41e6405197b069629b902e51":{
      "scriptId":"u88"},
    "3f1e5ee6261d4c5e81c9f4d14f3b9f4c":{
      "scriptId":"u89"},
    "99e2d1c3c96a45e0a915a068b651fe47":{
      "scriptId":"u90"},
    "0fbdff61870748ffa2ec0f851b866692":{
      "scriptId":"u91"},
    "5ef561c470e14da2abf3cd4ab1a32923":{
      "scriptId":"u92"},
    "1893c91af1fb41ada800a479dbc4e40e":{
      "scriptId":"u93"},
    "74a72ab2910c49f095b3bd5803e3eccc":{
      "scriptId":"u94"},
    "b7462b9486e945608e5f3c0de34de225":{
      "scriptId":"u95"},
    "28dca5c155884a9f8b3fe499c2688df7":{
      "scriptId":"u96"},
    "b3239c70c77442d693fbac17a0554c10":{
      "scriptId":"u97"}}});