$axure.loadCurrentPage({
  "url":"music.html",
  "generationDate":new Date(1400036939710.07),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5bfb36c495384c02a63037e24b095dbb",
    "type":"Axure:Page",
    "name":"Music",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9678b1d73b694eae9ffb775a521074fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":640},
            "size":{
              "width":950,
              "height":800},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fef63248c3f49ddbf55d00abcfd0681",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":640},
                "size":{
                  "width":950,
                  "height":800},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/music/u0.png"}},
{
          "id":"46bdc6a71bda4d8c9cdc65158128d01e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":20}},
          "adaptiveStyles":{
},
          "masterId":"7eca3fcc01c445f79a990fdeb99a5cab"},
{
          "id":"07c55026f3424102951eefe67fccb616",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":110},
            "size":{
              "width":950,
              "height":510},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96856ceaab294bbaab97e62c2b8b54b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":110},
                "size":{
                  "width":950,
                  "height":510},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/events/u0.png"}},
{
          "id":"6aea3533b35449ca8f0b5a0726eb537d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":220},
            "size":{
              "width":870,
              "height":360}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"601d116fa32a4dea9a4e2abea7883a5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":220},
                "size":{
                  "width":870,
                  "height":360}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/gallery/u27.png"}},
{
          "id":"1ddec7de590e41ce9671605e5d34eb24",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'OpenSans-Semibold', 'Open Sans Semibold', 'Open Sans'",
            "fontWeight":"650",
            "location":{
              "x":468,
              "y":141},
            "size":{
              "width":102,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"746c3d4131c24964a7363e9339c6d3da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'OpenSans-Semibold', 'Open Sans Semibold', 'Open Sans'",
                "fontWeight":"650",
                "location":{
                  "x":468,
                  "y":141},
                "size":{
                  "width":102,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b28f0c18e5d4dabada60268d238f18a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":381,
              "y":185},
            "size":{
              "width":319,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/gallery/u35_line.png"}},
{
          "id":"6e543c1ce0964bcc9e0169a85fd98155",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "location":{
              "x":90,
              "y":660},
            "size":{
              "width":560,
              "height":740}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bddeabde8354a2ab044d4a590a62ea2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "location":{
                  "x":90,
                  "y":660},
                "size":{
                  "width":560,
                  "height":740}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/music/u34.png"}},
{
          "id":"68d8b4d58ef947d0b862a7f195359ccb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":850},
            "size":{
              "width":217,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/about/u50_line.png"}},
{
          "id":"db7ab0f33b4a443eab24497f3869203d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":872},
            "size":{
              "width":250,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/about/u51_line.png"}},
{
          "id":"af686b25baf84a88bdff81d2bba59589",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":894},
            "size":{
              "width":217,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/about/u50_line.png"}},
{
          "id":"045057081964474cbb9ed058fb60fe07",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":914},
            "size":{
              "width":250,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/about/u51_line.png"}},
{
          "id":"f7550589cb734bb5b73406a5f8c9a3e7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":936},
            "size":{
              "width":217,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/about/u50_line.png"}},
{
          "id":"62612cda9ec44da0b48efd17b3d4bdbb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":956},
            "size":{
              "width":250,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/about/u51_line.png"}},
{
          "id":"82bdd4513b564a7180be3ebb7d09c08a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":978},
            "size":{
              "width":217,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/about/u50_line.png"}},
{
          "id":"6291d8c72a5d40a4b03b3c038a296155",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":762},
            "size":{
              "width":238,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"332afecffb674fa0a343384e342e77fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":700,
                  "y":762},
                "size":{
                  "width":238,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b06120999cec41e48d5ad7b06a3a6865",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":1460}},
          "adaptiveStyles":{
},
          "masterId":"8b72bd043b4a4566adb151b8a50c1f55"}]}},
  "masters":{
    "7eca3fcc01c445f79a990fdeb99a5cab":{
      "packageId":"7eca3fcc01c445f79a990fdeb99a5cab",
      "type":"Axure:Master",
      "name":"Navigation#2",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"d96b73e5116343d7a7cead3ca585ff24",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":380,
                "y":0},
              "size":{
                "width":620,
                "height":50},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e675e991c3554e23bb87e8d8f07a67cf",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":380,
                    "y":0},
                  "size":{
                    "width":620,
                    "height":50},
                  "borderWidth":"2",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u5.png"}},
{
            "id":"12243ac1b8de4099938d278e1f17e40d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
              "fontSize":"20px",
              "fontWeight":"200",
              "location":{
                "x":386,
                "y":10},
              "size":{
                "width":111,
                "height":30},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF009933},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dc621ca7d2cf41a894fdb5b2a29bc857",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
                  "fontSize":"20px",
                  "fontWeight":"200",
                  "location":{
                    "x":386,
                    "y":10},
                  "size":{
                    "width":111,
                    "height":30},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF009933},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u7.png"}},
{
            "id":"91551619f67046c88400c5a9b194776b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
              "fontSize":"20px",
              "fontWeight":"200",
              "location":{
                "x":505,
                "y":10},
              "size":{
                "width":111,
                "height":30},
              "borderWidth":"-1",
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"19affa3f6d43477b9bfd2761dcddd3ae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
                  "fontSize":"20px",
                  "fontWeight":"200",
                  "location":{
                    "x":505,
                    "y":10},
                  "size":{
                    "width":111,
                    "height":30},
                  "borderWidth":"-1",
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open About in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"about.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u9.png"}},
{
            "id":"f2a6d3cab7354367999f0e4a4701c391",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
              "fontSize":"20px",
              "fontWeight":"200",
              "location":{
                "x":624,
                "y":10},
              "size":{
                "width":111,
                "height":30},
              "borderWidth":"-1",
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8375330ccaab4868ac01adeac3998c7b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
                  "fontSize":"20px",
                  "fontWeight":"200",
                  "location":{
                    "x":624,
                    "y":10},
                  "size":{
                    "width":111,
                    "height":30},
                  "borderWidth":"-1",
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Events in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"events.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u9.png"}},
{
            "id":"ecd472da246a4b0ebde176f8cf654db0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
              "fontSize":"20px",
              "fontWeight":"200",
              "location":{
                "x":745,
                "y":10},
              "size":{
                "width":111,
                "height":30},
              "borderWidth":"-1",
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7324f80ca2fe4e32ac07761ad6e447ed",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
                  "fontSize":"20px",
                  "fontWeight":"200",
                  "location":{
                    "x":745,
                    "y":10},
                  "size":{
                    "width":111,
                    "height":30},
                  "borderWidth":"-1",
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show MediaFlyout treat as flyout",
                        "objectsToFades":[{
                            "objectPath":["e667355ff9d3481087a63a2969446b1f"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"flyout"}}}]}]}]}},
            "images":{
              "normal~":"images/home/u9.png"}},
{
            "id":"748b192633a9422ea3d447d9511e8dee",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
              "fontSize":"20px",
              "fontWeight":"200",
              "location":{
                "x":867,
                "y":10},
              "size":{
                "width":111,
                "height":30},
              "borderWidth":"-1",
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2f01050f65424488a5b2a138706ce60e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
                  "fontSize":"20px",
                  "fontWeight":"200",
                  "location":{
                    "x":867,
                    "y":10},
                  "size":{
                    "width":111,
                    "height":30},
                  "borderWidth":"-1",
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Contact in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contact.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u9.png"}},
{
            "id":"e667355ff9d3481087a63a2969446b1f",
            "label":"MediaFlyout",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":739,
                "y":50},
              "size":{
                "width":160,
                "height":114},
              "visible":false},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"3dca0436bbfd4ad8b4c6dfb5ad56df4b",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"390cf107ac7d47c6bc44886f986313e5",
                    "label":"",
                    "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC},
                      "size":{
                        "width":160,
                        "height":114},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFAEAEAE}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"f8d846addf9d44219093509b900f40b3",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC},
                          "size":{
                            "width":160,
                            "height":114},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFAEAEAE}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/u18.png"}},
{
                    "id":"3a6132e387424d6fbbf2248b3654016c",
                    "label":"",
                    "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC},
                      "location":{
                        "x":14,
                        "y":11},
                      "size":{
                        "width":138,
                        "height":20},
                      "borderWidth":"-1",
                      "cornerRadiusTopLeft":"5"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"aba5fdd5f99240e3ab65e051386a96c5",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC},
                          "location":{
                            "x":14,
                            "y":11},
                          "size":{
                            "width":138,
                            "height":20},
                          "borderWidth":"-1",
                          "cornerRadiusTopLeft":"5"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Gallery in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"gallery.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u20.png"}},
{
                    "id":"6889745b526b4678a3382c3ecc3ca560",
                    "label":"",
                    "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC},
                      "location":{
                        "x":14,
                        "y":48},
                      "size":{
                        "width":138,
                        "height":20},
                      "borderWidth":"-1",
                      "cornerRadiusTopLeft":"5"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2bdce835ad7341c099f582ef7f5739a7",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC},
                          "location":{
                            "x":14,
                            "y":48},
                          "size":{
                            "width":138,
                            "height":20},
                          "borderWidth":"-1",
                          "cornerRadiusTopLeft":"5"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Music in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"music.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u20.png"}},
{
                    "id":"604d913d8219424b904ea3538c9e709d",
                    "label":"",
                    "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC},
                      "location":{
                        "x":14,
                        "y":83},
                      "size":{
                        "width":138,
                        "height":20},
                      "borderWidth":"-1",
                      "cornerRadiusTopLeft":"5"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0ab12be8507b4b5d96523b9689bef6d8",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC},
                          "location":{
                            "x":14,
                            "y":83},
                          "size":{
                            "width":138,
                            "height":20},
                          "borderWidth":"-1",
                          "cornerRadiusTopLeft":"5"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Video in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"video.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u20.png"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]},
{
            "id":"5a09e75d78154126b36e9e911c560920",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":54,
                "y":0},
              "size":{
                "width":280,
                "height":42}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bb7b3553b986493d94efa8d3936ba89e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":54,
                    "y":0},
                  "size":{
                    "width":280,
                    "height":42}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u26.png"}},
{
            "id":"a14ef670f2004442bc29daa99eee55ba",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":50,
                "y":54},
              "size":{
                "width":950,
                "height":10},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF999999}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/home/u28_line.png"}}]}},
    "8b72bd043b4a4566adb151b8a50c1f55":{
      "packageId":"8b72bd043b4a4566adb151b8a50c1f55",
      "type":"Axure:Master",
      "name":"Footer",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"20f3cd74ae3948eb9611ff6704f923e8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
              "fontWeight":"700",
              "fill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "location":{
                "x":-100,
                "y":0},
              "size":{
                "width":950,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"21b4e9ebc28c473dab39ebcb625bdf01",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
                  "fontWeight":"700",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "location":{
                    "x":-100,
                    "y":0},
                  "size":{
                    "width":950,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u71.png"}}]}}},
  "objectPaths":{
    "9678b1d73b694eae9ffb775a521074fc":{
      "scriptId":"u0"},
    "9fef63248c3f49ddbf55d00abcfd0681":{
      "scriptId":"u1"},
    "46bdc6a71bda4d8c9cdc65158128d01e":{
      "scriptId":"u2",
      "d96b73e5116343d7a7cead3ca585ff24":{
        "scriptId":"u3"},
      "e675e991c3554e23bb87e8d8f07a67cf":{
        "scriptId":"u4"},
      "12243ac1b8de4099938d278e1f17e40d":{
        "scriptId":"u5"},
      "dc621ca7d2cf41a894fdb5b2a29bc857":{
        "scriptId":"u6"},
      "91551619f67046c88400c5a9b194776b":{
        "scriptId":"u7"},
      "19affa3f6d43477b9bfd2761dcddd3ae":{
        "scriptId":"u8"},
      "f2a6d3cab7354367999f0e4a4701c391":{
        "scriptId":"u9"},
      "8375330ccaab4868ac01adeac3998c7b":{
        "scriptId":"u10"},
      "ecd472da246a4b0ebde176f8cf654db0":{
        "scriptId":"u11"},
      "7324f80ca2fe4e32ac07761ad6e447ed":{
        "scriptId":"u12"},
      "748b192633a9422ea3d447d9511e8dee":{
        "scriptId":"u13"},
      "2f01050f65424488a5b2a138706ce60e":{
        "scriptId":"u14"},
      "e667355ff9d3481087a63a2969446b1f":{
        "scriptId":"u15"},
      "390cf107ac7d47c6bc44886f986313e5":{
        "scriptId":"u16"},
      "f8d846addf9d44219093509b900f40b3":{
        "scriptId":"u17"},
      "3a6132e387424d6fbbf2248b3654016c":{
        "scriptId":"u18"},
      "aba5fdd5f99240e3ab65e051386a96c5":{
        "scriptId":"u19"},
      "6889745b526b4678a3382c3ecc3ca560":{
        "scriptId":"u20"},
      "2bdce835ad7341c099f582ef7f5739a7":{
        "scriptId":"u21"},
      "604d913d8219424b904ea3538c9e709d":{
        "scriptId":"u22"},
      "0ab12be8507b4b5d96523b9689bef6d8":{
        "scriptId":"u23"},
      "5a09e75d78154126b36e9e911c560920":{
        "scriptId":"u24"},
      "bb7b3553b986493d94efa8d3936ba89e":{
        "scriptId":"u25"},
      "a14ef670f2004442bc29daa99eee55ba":{
        "scriptId":"u26"}},
    "07c55026f3424102951eefe67fccb616":{
      "scriptId":"u27"},
    "96856ceaab294bbaab97e62c2b8b54b7":{
      "scriptId":"u28"},
    "6aea3533b35449ca8f0b5a0726eb537d":{
      "scriptId":"u29"},
    "601d116fa32a4dea9a4e2abea7883a5a":{
      "scriptId":"u30"},
    "1ddec7de590e41ce9671605e5d34eb24":{
      "scriptId":"u31"},
    "746c3d4131c24964a7363e9339c6d3da":{
      "scriptId":"u32"},
    "6b28f0c18e5d4dabada60268d238f18a":{
      "scriptId":"u33"},
    "6e543c1ce0964bcc9e0169a85fd98155":{
      "scriptId":"u34"},
    "1bddeabde8354a2ab044d4a590a62ea2":{
      "scriptId":"u35"},
    "68d8b4d58ef947d0b862a7f195359ccb":{
      "scriptId":"u36"},
    "db7ab0f33b4a443eab24497f3869203d":{
      "scriptId":"u37"},
    "af686b25baf84a88bdff81d2bba59589":{
      "scriptId":"u38"},
    "045057081964474cbb9ed058fb60fe07":{
      "scriptId":"u39"},
    "f7550589cb734bb5b73406a5f8c9a3e7":{
      "scriptId":"u40"},
    "62612cda9ec44da0b48efd17b3d4bdbb":{
      "scriptId":"u41"},
    "82bdd4513b564a7180be3ebb7d09c08a":{
      "scriptId":"u42"},
    "6291d8c72a5d40a4b03b3c038a296155":{
      "scriptId":"u43"},
    "332afecffb674fa0a343384e342e77fe":{
      "scriptId":"u44"},
    "b06120999cec41e48d5ad7b06a3a6865":{
      "scriptId":"u45",
      "20f3cd74ae3948eb9611ff6704f923e8":{
        "scriptId":"u46"},
      "21b4e9ebc28c473dab39ebcb625bdf01":{
        "scriptId":"u47"}}}});