$axure.loadCurrentPage({
  "url":"events.html",
  "generationDate":new Date(1400036938126.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ab234a43788d49599610538968a6fa40",
    "type":"Axure:Page",
    "name":"Events",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8f3b568395714054a1ba0e96a9e0b7ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":120},
            "size":{
              "width":950,
              "height":510},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c438a98ab874b8a88be1085c4b2b279",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":120},
                "size":{
                  "width":950,
                  "height":510},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/events/u0.png"}},
{
          "id":"61b548677d374d99a0aaaeacdacd18a8",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":10}},
          "adaptiveStyles":{
},
          "masterId":"7eca3fcc01c445f79a990fdeb99a5cab"},
{
          "id":"bdd8953220e345a08a2b7c29206d7e56",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'OpenSans-Semibold', 'Open Sans Semibold', 'Open Sans'",
            "fontWeight":"650",
            "location":{
              "x":480,
              "y":153},
            "size":{
              "width":117,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48926b9e481b4bd6b4382585a02a4606",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'OpenSans-Semibold', 'Open Sans Semibold', 'Open Sans'",
                "fontWeight":"650",
                "location":{
                  "x":480,
                  "y":153},
                "size":{
                  "width":117,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d33b1600f10447498babc21a3fd1ebb1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":220},
            "size":{
              "width":490,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/events/u29_line.png"}},
{
          "id":"c864584722854825b3c89ea72f140502",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":262},
            "size":{
              "width":306,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02f861b5cf3043d1b78511ff50c8f5b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":262},
                "size":{
                  "width":306,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da7df36f50474cd68caaa76f4a242294",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":107,
              "y":312},
            "size":{
              "width":487,
              "height":270}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"269c8c1287e54e009097dbb74470de07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":107,
                  "y":312},
                "size":{
                  "width":487,
                  "height":270}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/events/u32.png"}},
{
          "id":"df8a07a435fe4150938d248639586626",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'OpenSans', 'Open Sans'",
            "location":{
              "x":604,
              "y":312},
            "size":{
              "width":396,
              "height":116}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1879b4c4c87541c385d1ed3aad0ba3c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'OpenSans', 'Open Sans'",
                "location":{
                  "x":604,
                  "y":312},
                "size":{
                  "width":396,
                  "height":116}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b6d851b4dc64a8a91c28e83b4c37b26",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":438},
            "size":{
              "width":217,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/about/u50_line.png"}},
{
          "id":"fbb49cfa91c64e2ba01153ef7e226534",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":460},
            "size":{
              "width":250,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/about/u51_line.png"}},
{
          "id":"19ec4a32564e47fabf4558c38949b629",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":482},
            "size":{
              "width":217,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/about/u50_line.png"}},
{
          "id":"1e200d300aea452c9c3cdd23005693ec",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":502},
            "size":{
              "width":250,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/about/u51_line.png"}},
{
          "id":"bfb1bc1deb9641179c10fe1d9495e3bf",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":524},
            "size":{
              "width":217,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/about/u50_line.png"}},
{
          "id":"ca559ff652c8455eaf79f14f3e08b752",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":544},
            "size":{
              "width":250,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/about/u51_line.png"}},
{
          "id":"2a270f6fbc1343f494a50008c29066bc",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":566},
            "size":{
              "width":217,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/about/u50_line.png"}},
{
          "id":"9e5a809248e64791a53f64b63bf4f574",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":670},
            "size":{
              "width":950,
              "height":420},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efca6ac014fb4c6db763a229122e4977",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":670},
                "size":{
                  "width":950,
                  "height":420},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/events/u43.png"}},
{
          "id":"4d76db4b4fc348db95ce309f43bd3a18",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":107,
              "y":702},
            "size":{
              "width":299,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f866107d8b2244c399dd819747ae6de4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":107,
                  "y":702},
                "size":{
                  "width":299,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db941276a7f348f0803457d2270dfc97",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":107,
              "y":760},
            "size":{
              "width":487,
              "height":270}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0558a173172548e09c87528b8dfd908c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":107,
                  "y":760},
                "size":{
                  "width":487,
                  "height":270}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/events/u32.png"}},
{
          "id":"e6e6c901188543a69ad2e6c470e1bc7f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":886},
            "size":{
              "width":217,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/about/u50_line.png"}},
{
          "id":"31bf585ddf934f7e8afab4115d9f386b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":908},
            "size":{
              "width":250,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/about/u51_line.png"}},
{
          "id":"3a3a8e9d2a684c79be93d914abb277a7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":930},
            "size":{
              "width":217,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/about/u50_line.png"}},
{
          "id":"8ef8b947c67c48a1881bc202e8743124",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":950},
            "size":{
              "width":250,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/about/u51_line.png"}},
{
          "id":"bc93a9bcf87a4696ab6b1d2c94373f51",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":972},
            "size":{
              "width":217,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/about/u50_line.png"}},
{
          "id":"8220795b115d48b2add51bf1e3a26fd4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":992},
            "size":{
              "width":250,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/about/u51_line.png"}},
{
          "id":"fc1abdaf2cd5447eaccae69558f601cb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":1014},
            "size":{
              "width":217,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/about/u50_line.png"}},
{
          "id":"747ebf9941f14efaba760c34a1b9422d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'OpenSans', 'Open Sans'",
            "location":{
              "x":604,
              "y":760},
            "size":{
              "width":396,
              "height":116}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"475d4458eb294c6f8585fa20a746942f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'OpenSans', 'Open Sans'",
                "location":{
                  "x":604,
                  "y":760},
                "size":{
                  "width":396,
                  "height":116}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"631af202336747009bfdd9f753f6fd8e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":1110}},
          "adaptiveStyles":{
},
          "masterId":"8b72bd043b4a4566adb151b8a50c1f55"}]}},
  "masters":{
    "7eca3fcc01c445f79a990fdeb99a5cab":{
      "packageId":"7eca3fcc01c445f79a990fdeb99a5cab",
      "type":"Axure:Master",
      "name":"Navigation#2",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"d96b73e5116343d7a7cead3ca585ff24",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":380,
                "y":0},
              "size":{
                "width":620,
                "height":50},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e675e991c3554e23bb87e8d8f07a67cf",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":380,
                    "y":0},
                  "size":{
                    "width":620,
                    "height":50},
                  "borderWidth":"2",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u5.png"}},
{
            "id":"12243ac1b8de4099938d278e1f17e40d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
              "fontSize":"20px",
              "fontWeight":"200",
              "location":{
                "x":386,
                "y":10},
              "size":{
                "width":111,
                "height":30},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF009933},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dc621ca7d2cf41a894fdb5b2a29bc857",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
                  "fontSize":"20px",
                  "fontWeight":"200",
                  "location":{
                    "x":386,
                    "y":10},
                  "size":{
                    "width":111,
                    "height":30},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF009933},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u7.png"}},
{
            "id":"91551619f67046c88400c5a9b194776b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
              "fontSize":"20px",
              "fontWeight":"200",
              "location":{
                "x":505,
                "y":10},
              "size":{
                "width":111,
                "height":30},
              "borderWidth":"-1",
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"19affa3f6d43477b9bfd2761dcddd3ae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
                  "fontSize":"20px",
                  "fontWeight":"200",
                  "location":{
                    "x":505,
                    "y":10},
                  "size":{
                    "width":111,
                    "height":30},
                  "borderWidth":"-1",
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open About in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"about.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u9.png"}},
{
            "id":"f2a6d3cab7354367999f0e4a4701c391",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
              "fontSize":"20px",
              "fontWeight":"200",
              "location":{
                "x":624,
                "y":10},
              "size":{
                "width":111,
                "height":30},
              "borderWidth":"-1",
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8375330ccaab4868ac01adeac3998c7b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
                  "fontSize":"20px",
                  "fontWeight":"200",
                  "location":{
                    "x":624,
                    "y":10},
                  "size":{
                    "width":111,
                    "height":30},
                  "borderWidth":"-1",
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Events in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"events.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u9.png"}},
{
            "id":"ecd472da246a4b0ebde176f8cf654db0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
              "fontSize":"20px",
              "fontWeight":"200",
              "location":{
                "x":745,
                "y":10},
              "size":{
                "width":111,
                "height":30},
              "borderWidth":"-1",
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7324f80ca2fe4e32ac07761ad6e447ed",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
                  "fontSize":"20px",
                  "fontWeight":"200",
                  "location":{
                    "x":745,
                    "y":10},
                  "size":{
                    "width":111,
                    "height":30},
                  "borderWidth":"-1",
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show MediaFlyout treat as flyout",
                        "objectsToFades":[{
                            "objectPath":["e667355ff9d3481087a63a2969446b1f"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"flyout"}}}]}]}]}},
            "images":{
              "normal~":"images/home/u9.png"}},
{
            "id":"748b192633a9422ea3d447d9511e8dee",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
              "fontSize":"20px",
              "fontWeight":"200",
              "location":{
                "x":867,
                "y":10},
              "size":{
                "width":111,
                "height":30},
              "borderWidth":"-1",
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2f01050f65424488a5b2a138706ce60e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
                  "fontSize":"20px",
                  "fontWeight":"200",
                  "location":{
                    "x":867,
                    "y":10},
                  "size":{
                    "width":111,
                    "height":30},
                  "borderWidth":"-1",
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Contact in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contact.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u9.png"}},
{
            "id":"e667355ff9d3481087a63a2969446b1f",
            "label":"MediaFlyout",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":739,
                "y":50},
              "size":{
                "width":160,
                "height":114},
              "visible":false},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"3dca0436bbfd4ad8b4c6dfb5ad56df4b",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"390cf107ac7d47c6bc44886f986313e5",
                    "label":"",
                    "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC},
                      "size":{
                        "width":160,
                        "height":114},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFAEAEAE}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"f8d846addf9d44219093509b900f40b3",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC},
                          "size":{
                            "width":160,
                            "height":114},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFAEAEAE}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/u18.png"}},
{
                    "id":"3a6132e387424d6fbbf2248b3654016c",
                    "label":"",
                    "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC},
                      "location":{
                        "x":14,
                        "y":11},
                      "size":{
                        "width":138,
                        "height":20},
                      "borderWidth":"-1",
                      "cornerRadiusTopLeft":"5"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"aba5fdd5f99240e3ab65e051386a96c5",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC},
                          "location":{
                            "x":14,
                            "y":11},
                          "size":{
                            "width":138,
                            "height":20},
                          "borderWidth":"-1",
                          "cornerRadiusTopLeft":"5"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Gallery in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"gallery.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u20.png"}},
{
                    "id":"6889745b526b4678a3382c3ecc3ca560",
                    "label":"",
                    "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC},
                      "location":{
                        "x":14,
                        "y":48},
                      "size":{
                        "width":138,
                        "height":20},
                      "borderWidth":"-1",
                      "cornerRadiusTopLeft":"5"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2bdce835ad7341c099f582ef7f5739a7",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC},
                          "location":{
                            "x":14,
                            "y":48},
                          "size":{
                            "width":138,
                            "height":20},
                          "borderWidth":"-1",
                          "cornerRadiusTopLeft":"5"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Music in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"music.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u20.png"}},
{
                    "id":"604d913d8219424b904ea3538c9e709d",
                    "label":"",
                    "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC},
                      "location":{
                        "x":14,
                        "y":83},
                      "size":{
                        "width":138,
                        "height":20},
                      "borderWidth":"-1",
                      "cornerRadiusTopLeft":"5"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0ab12be8507b4b5d96523b9689bef6d8",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC},
                          "location":{
                            "x":14,
                            "y":83},
                          "size":{
                            "width":138,
                            "height":20},
                          "borderWidth":"-1",
                          "cornerRadiusTopLeft":"5"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Video in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"video.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u20.png"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]},
{
            "id":"5a09e75d78154126b36e9e911c560920",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":54,
                "y":0},
              "size":{
                "width":280,
                "height":42}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bb7b3553b986493d94efa8d3936ba89e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":54,
                    "y":0},
                  "size":{
                    "width":280,
                    "height":42}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u26.png"}},
{
            "id":"a14ef670f2004442bc29daa99eee55ba",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":50,
                "y":54},
              "size":{
                "width":950,
                "height":10},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF999999}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/home/u28_line.png"}}]}},
    "8b72bd043b4a4566adb151b8a50c1f55":{
      "packageId":"8b72bd043b4a4566adb151b8a50c1f55",
      "type":"Axure:Master",
      "name":"Footer",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"20f3cd74ae3948eb9611ff6704f923e8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
              "fontWeight":"700",
              "fill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "location":{
                "x":-100,
                "y":0},
              "size":{
                "width":950,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"21b4e9ebc28c473dab39ebcb625bdf01",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
                  "fontWeight":"700",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "location":{
                    "x":-100,
                    "y":0},
                  "size":{
                    "width":950,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u71.png"}}]}}},
  "objectPaths":{
    "8f3b568395714054a1ba0e96a9e0b7ca":{
      "scriptId":"u0"},
    "1c438a98ab874b8a88be1085c4b2b279":{
      "scriptId":"u1"},
    "61b548677d374d99a0aaaeacdacd18a8":{
      "scriptId":"u2",
      "d96b73e5116343d7a7cead3ca585ff24":{
        "scriptId":"u3"},
      "e675e991c3554e23bb87e8d8f07a67cf":{
        "scriptId":"u4"},
      "12243ac1b8de4099938d278e1f17e40d":{
        "scriptId":"u5"},
      "dc621ca7d2cf41a894fdb5b2a29bc857":{
        "scriptId":"u6"},
      "91551619f67046c88400c5a9b194776b":{
        "scriptId":"u7"},
      "19affa3f6d43477b9bfd2761dcddd3ae":{
        "scriptId":"u8"},
      "f2a6d3cab7354367999f0e4a4701c391":{
        "scriptId":"u9"},
      "8375330ccaab4868ac01adeac3998c7b":{
        "scriptId":"u10"},
      "ecd472da246a4b0ebde176f8cf654db0":{
        "scriptId":"u11"},
      "7324f80ca2fe4e32ac07761ad6e447ed":{
        "scriptId":"u12"},
      "748b192633a9422ea3d447d9511e8dee":{
        "scriptId":"u13"},
      "2f01050f65424488a5b2a138706ce60e":{
        "scriptId":"u14"},
      "e667355ff9d3481087a63a2969446b1f":{
        "scriptId":"u15"},
      "390cf107ac7d47c6bc44886f986313e5":{
        "scriptId":"u16"},
      "f8d846addf9d44219093509b900f40b3":{
        "scriptId":"u17"},
      "3a6132e387424d6fbbf2248b3654016c":{
        "scriptId":"u18"},
      "aba5fdd5f99240e3ab65e051386a96c5":{
        "scriptId":"u19"},
      "6889745b526b4678a3382c3ecc3ca560":{
        "scriptId":"u20"},
      "2bdce835ad7341c099f582ef7f5739a7":{
        "scriptId":"u21"},
      "604d913d8219424b904ea3538c9e709d":{
        "scriptId":"u22"},
      "0ab12be8507b4b5d96523b9689bef6d8":{
        "scriptId":"u23"},
      "5a09e75d78154126b36e9e911c560920":{
        "scriptId":"u24"},
      "bb7b3553b986493d94efa8d3936ba89e":{
        "scriptId":"u25"},
      "a14ef670f2004442bc29daa99eee55ba":{
        "scriptId":"u26"}},
    "bdd8953220e345a08a2b7c29206d7e56":{
      "scriptId":"u27"},
    "48926b9e481b4bd6b4382585a02a4606":{
      "scriptId":"u28"},
    "d33b1600f10447498babc21a3fd1ebb1":{
      "scriptId":"u29"},
    "c864584722854825b3c89ea72f140502":{
      "scriptId":"u30"},
    "02f861b5cf3043d1b78511ff50c8f5b8":{
      "scriptId":"u31"},
    "da7df36f50474cd68caaa76f4a242294":{
      "scriptId":"u32"},
    "269c8c1287e54e009097dbb74470de07":{
      "scriptId":"u33"},
    "df8a07a435fe4150938d248639586626":{
      "scriptId":"u34"},
    "1879b4c4c87541c385d1ed3aad0ba3c5":{
      "scriptId":"u35"},
    "0b6d851b4dc64a8a91c28e83b4c37b26":{
      "scriptId":"u36"},
    "fbb49cfa91c64e2ba01153ef7e226534":{
      "scriptId":"u37"},
    "19ec4a32564e47fabf4558c38949b629":{
      "scriptId":"u38"},
    "1e200d300aea452c9c3cdd23005693ec":{
      "scriptId":"u39"},
    "bfb1bc1deb9641179c10fe1d9495e3bf":{
      "scriptId":"u40"},
    "ca559ff652c8455eaf79f14f3e08b752":{
      "scriptId":"u41"},
    "2a270f6fbc1343f494a50008c29066bc":{
      "scriptId":"u42"},
    "9e5a809248e64791a53f64b63bf4f574":{
      "scriptId":"u43"},
    "efca6ac014fb4c6db763a229122e4977":{
      "scriptId":"u44"},
    "4d76db4b4fc348db95ce309f43bd3a18":{
      "scriptId":"u45"},
    "f866107d8b2244c399dd819747ae6de4":{
      "scriptId":"u46"},
    "db941276a7f348f0803457d2270dfc97":{
      "scriptId":"u47"},
    "0558a173172548e09c87528b8dfd908c":{
      "scriptId":"u48"},
    "e6e6c901188543a69ad2e6c470e1bc7f":{
      "scriptId":"u49"},
    "31bf585ddf934f7e8afab4115d9f386b":{
      "scriptId":"u50"},
    "3a3a8e9d2a684c79be93d914abb277a7":{
      "scriptId":"u51"},
    "8ef8b947c67c48a1881bc202e8743124":{
      "scriptId":"u52"},
    "bc93a9bcf87a4696ab6b1d2c94373f51":{
      "scriptId":"u53"},
    "8220795b115d48b2add51bf1e3a26fd4":{
      "scriptId":"u54"},
    "fc1abdaf2cd5447eaccae69558f601cb":{
      "scriptId":"u55"},
    "747ebf9941f14efaba760c34a1b9422d":{
      "scriptId":"u56"},
    "475d4458eb294c6f8585fa20a746942f":{
      "scriptId":"u57"},
    "631af202336747009bfdd9f753f6fd8e":{
      "scriptId":"u58",
      "20f3cd74ae3948eb9611ff6704f923e8":{
        "scriptId":"u59"},
      "21b4e9ebc28c473dab39ebcb625bdf01":{
        "scriptId":"u60"}}}});