$axure.loadCurrentPage({
  "url":"gallery.html",
  "generationDate":new Date(1400036938820.73),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2cba4d147daf41499e5b61f80632a005",
    "type":"Axure:Page",
    "name":"Gallery",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5501853d56524250b75c611f6c0d3486",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":20}},
          "adaptiveStyles":{
},
          "masterId":"7eca3fcc01c445f79a990fdeb99a5cab"},
{
          "id":"ec4f40c8ea25448798f55ff492171af3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":110},
            "size":{
              "width":950,
              "height":510},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d21a472b3b04e02bc98399cfa38d373",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":110},
                "size":{
                  "width":950,
                  "height":510},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/events/u0.png"}},
{
          "id":"d82dd0e104d64c7c8e4eb0a8eeef7dce",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":220},
            "size":{
              "width":870,
              "height":360}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af9ee092195b45f082474bc8586eff9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":220},
                "size":{
                  "width":870,
                  "height":360}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/gallery/u27.png"}},
{
          "id":"f467c351e8df427cb2ece7a99d938ea1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'OpenSans-Semibold', 'Open Sans Semibold', 'Open Sans'",
            "fontWeight":"650",
            "location":{
              "x":478,
              "y":141},
            "size":{
              "width":137,
              "height":43}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f3afb451d934ce19a4688a28343379d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'OpenSans-Semibold', 'Open Sans Semibold', 'Open Sans'",
                "fontWeight":"650",
                "location":{
                  "x":478,
                  "y":141},
                "size":{
                  "width":137,
                  "height":43}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0251e17805842d08e330601ab4c2643",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":650.000061035156},
            "size":{
              "width":950,
              "height":670},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da4ff92f00c0476daedc7347e18f2c57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":650.000061035156},
                "size":{
                  "width":950,
                  "height":670},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/gallery/u31.png"}},
{
          "id":"52034d29eb194f32b4be4cd82e5bc1ee",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":245,
              "y":680},
            "size":{
              "width":610,
              "height":400}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb5f4b0050b940b98f8f89ea252d1334",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":245,
                  "y":680},
                "size":{
                  "width":610,
                  "height":400}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/gallery/u33.png"}},
{
          "id":"db9ede3a09a1467c82d568a56ac6942c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":391,
              "y":185},
            "size":{
              "width":319,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/gallery/u35_line.png"}},
{
          "id":"b5787e7dfdd04185b45edb5ba6b4d84e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":920,
              "y":865},
            "size":{
              "width":50,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6090227c2de5406eb47239df0ff661a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":920,
                  "y":865},
                "size":{
                  "width":50,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/gallery/u36.png"}},
{
          "id":"d1b3cf4405174580a0fd4cdddf11e415",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":134,
              "y":865},
            "size":{
              "width":50,
              "height":30},
            "rotation":"180",
            "textRotation":"180",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94c78b94378843e7b1b127bd670c5e1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":134,
                  "y":865},
                "size":{
                  "width":50,
                  "height":30},
                "rotation":"180",
                "textRotation":"180",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/gallery/u38.png"}},
{
          "id":"02ef2807bda94982972ba677cc39b1b9",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":1150},
            "size":{
              "width":910,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3c867af4d0847fdbbc06c39c9661c40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":1150},
                "size":{
                  "width":910,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/gallery/u40.png"}},
{
          "id":"46cd8ff7193e49e4b291ffe07eda67cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "location":{
              "x":455,
              "y":830},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2a8ede4a4bd4587be6df333766540c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "location":{
                  "x":455,
                  "y":830},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/gallery/u42.png"}},
{
          "id":"db901cb4e32d44b68f9f44f1a1ba8f1b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":1340}},
          "adaptiveStyles":{
},
          "masterId":"8b72bd043b4a4566adb151b8a50c1f55"}]}},
  "masters":{
    "7eca3fcc01c445f79a990fdeb99a5cab":{
      "packageId":"7eca3fcc01c445f79a990fdeb99a5cab",
      "type":"Axure:Master",
      "name":"Navigation#2",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"d96b73e5116343d7a7cead3ca585ff24",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":380,
                "y":0},
              "size":{
                "width":620,
                "height":50},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e675e991c3554e23bb87e8d8f07a67cf",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":380,
                    "y":0},
                  "size":{
                    "width":620,
                    "height":50},
                  "borderWidth":"2",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u5.png"}},
{
            "id":"12243ac1b8de4099938d278e1f17e40d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
              "fontSize":"20px",
              "fontWeight":"200",
              "location":{
                "x":386,
                "y":10},
              "size":{
                "width":111,
                "height":30},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF009933},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dc621ca7d2cf41a894fdb5b2a29bc857",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
                  "fontSize":"20px",
                  "fontWeight":"200",
                  "location":{
                    "x":386,
                    "y":10},
                  "size":{
                    "width":111,
                    "height":30},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF009933},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u7.png"}},
{
            "id":"91551619f67046c88400c5a9b194776b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
              "fontSize":"20px",
              "fontWeight":"200",
              "location":{
                "x":505,
                "y":10},
              "size":{
                "width":111,
                "height":30},
              "borderWidth":"-1",
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"19affa3f6d43477b9bfd2761dcddd3ae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
                  "fontSize":"20px",
                  "fontWeight":"200",
                  "location":{
                    "x":505,
                    "y":10},
                  "size":{
                    "width":111,
                    "height":30},
                  "borderWidth":"-1",
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open About in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"about.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u9.png"}},
{
            "id":"f2a6d3cab7354367999f0e4a4701c391",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
              "fontSize":"20px",
              "fontWeight":"200",
              "location":{
                "x":624,
                "y":10},
              "size":{
                "width":111,
                "height":30},
              "borderWidth":"-1",
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8375330ccaab4868ac01adeac3998c7b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
                  "fontSize":"20px",
                  "fontWeight":"200",
                  "location":{
                    "x":624,
                    "y":10},
                  "size":{
                    "width":111,
                    "height":30},
                  "borderWidth":"-1",
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Events in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"events.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u9.png"}},
{
            "id":"ecd472da246a4b0ebde176f8cf654db0",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
              "fontSize":"20px",
              "fontWeight":"200",
              "location":{
                "x":745,
                "y":10},
              "size":{
                "width":111,
                "height":30},
              "borderWidth":"-1",
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7324f80ca2fe4e32ac07761ad6e447ed",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
                  "fontSize":"20px",
                  "fontWeight":"200",
                  "location":{
                    "x":745,
                    "y":10},
                  "size":{
                    "width":111,
                    "height":30},
                  "borderWidth":"-1",
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"Show MediaFlyout treat as flyout",
                        "objectsToFades":[{
                            "objectPath":["e667355ff9d3481087a63a2969446b1f"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"flyout"}}}]}]}]}},
            "images":{
              "normal~":"images/home/u9.png"}},
{
            "id":"748b192633a9422ea3d447d9511e8dee",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
              "fontSize":"20px",
              "fontWeight":"200",
              "location":{
                "x":867,
                "y":10},
              "size":{
                "width":111,
                "height":30},
              "borderWidth":"-1",
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2f01050f65424488a5b2a138706ce60e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'OpenSans-Light', 'Open Sans Light', 'Open Sans'",
                  "fontSize":"20px",
                  "fontWeight":"200",
                  "location":{
                    "x":867,
                    "y":10},
                  "size":{
                    "width":111,
                    "height":30},
                  "borderWidth":"-1",
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Contact in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"contact.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u9.png"}},
{
            "id":"e667355ff9d3481087a63a2969446b1f",
            "label":"MediaFlyout",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":739,
                "y":50},
              "size":{
                "width":160,
                "height":114},
              "visible":false},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"3dca0436bbfd4ad8b4c6dfb5ad56df4b",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"390cf107ac7d47c6bc44886f986313e5",
                    "label":"",
                    "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC},
                      "size":{
                        "width":160,
                        "height":114},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFAEAEAE}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"f8d846addf9d44219093509b900f40b3",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC},
                          "size":{
                            "width":160,
                            "height":114},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFAEAEAE}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/home/u18.png"}},
{
                    "id":"3a6132e387424d6fbbf2248b3654016c",
                    "label":"",
                    "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC},
                      "location":{
                        "x":14,
                        "y":11},
                      "size":{
                        "width":138,
                        "height":20},
                      "borderWidth":"-1",
                      "cornerRadiusTopLeft":"5"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"aba5fdd5f99240e3ab65e051386a96c5",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC},
                          "location":{
                            "x":14,
                            "y":11},
                          "size":{
                            "width":138,
                            "height":20},
                          "borderWidth":"-1",
                          "cornerRadiusTopLeft":"5"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Gallery in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"gallery.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u20.png"}},
{
                    "id":"6889745b526b4678a3382c3ecc3ca560",
                    "label":"",
                    "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC},
                      "location":{
                        "x":14,
                        "y":48},
                      "size":{
                        "width":138,
                        "height":20},
                      "borderWidth":"-1",
                      "cornerRadiusTopLeft":"5"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"2bdce835ad7341c099f582ef7f5739a7",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC},
                          "location":{
                            "x":14,
                            "y":48},
                          "size":{
                            "width":138,
                            "height":20},
                          "borderWidth":"-1",
                          "cornerRadiusTopLeft":"5"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Music in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"music.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u20.png"}},
{
                    "id":"604d913d8219424b904ea3538c9e709d",
                    "label":"",
                    "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                    "panelIndex":0,
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC},
                      "location":{
                        "x":14,
                        "y":83},
                      "size":{
                        "width":138,
                        "height":20},
                      "borderWidth":"-1",
                      "cornerRadiusTopLeft":"5"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0ab12be8507b4b5d96523b9689bef6d8",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"e667355ff9d3481087a63a2969446b1f",
                        "panelIndex":0,
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFCCCCCC},
                          "location":{
                            "x":14,
                            "y":83},
                          "size":{
                            "width":138,
                            "height":20},
                          "borderWidth":"-1",
                          "cornerRadiusTopLeft":"5"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"Case 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"Open Video in Current Window",
                                "target":{
                                  "targetType":"page",
                                  "url":"video.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/home/u20.png"}}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]},
{
            "id":"5a09e75d78154126b36e9e911c560920",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":54,
                "y":0},
              "size":{
                "width":280,
                "height":42}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bb7b3553b986493d94efa8d3936ba89e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":54,
                    "y":0},
                  "size":{
                    "width":280,
                    "height":42}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open Home in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"home.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/home/u26.png"}},
{
            "id":"a14ef670f2004442bc29daa99eee55ba",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":50,
                "y":54},
              "size":{
                "width":950,
                "height":10},
              "borderWidth":"2",
              "borderFill":{
                "fillType":"solid",
                "color":0xFF999999}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/home/u28_line.png"}}]}},
    "8b72bd043b4a4566adb151b8a50c1f55":{
      "packageId":"8b72bd043b4a4566adb151b8a50c1f55",
      "type":"Axure:Master",
      "name":"Footer",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"20f3cd74ae3948eb9611ff6704f923e8",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
              "fontWeight":"700",
              "fill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "location":{
                "x":-100,
                "y":0},
              "size":{
                "width":950,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"21b4e9ebc28c473dab39ebcb625bdf01",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
                  "fontWeight":"700",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "location":{
                    "x":-100,
                    "y":0},
                  "size":{
                    "width":950,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/home/u71.png"}}]}}},
  "objectPaths":{
    "5501853d56524250b75c611f6c0d3486":{
      "scriptId":"u0",
      "d96b73e5116343d7a7cead3ca585ff24":{
        "scriptId":"u1"},
      "e675e991c3554e23bb87e8d8f07a67cf":{
        "scriptId":"u2"},
      "12243ac1b8de4099938d278e1f17e40d":{
        "scriptId":"u3"},
      "dc621ca7d2cf41a894fdb5b2a29bc857":{
        "scriptId":"u4"},
      "91551619f67046c88400c5a9b194776b":{
        "scriptId":"u5"},
      "19affa3f6d43477b9bfd2761dcddd3ae":{
        "scriptId":"u6"},
      "f2a6d3cab7354367999f0e4a4701c391":{
        "scriptId":"u7"},
      "8375330ccaab4868ac01adeac3998c7b":{
        "scriptId":"u8"},
      "ecd472da246a4b0ebde176f8cf654db0":{
        "scriptId":"u9"},
      "7324f80ca2fe4e32ac07761ad6e447ed":{
        "scriptId":"u10"},
      "748b192633a9422ea3d447d9511e8dee":{
        "scriptId":"u11"},
      "2f01050f65424488a5b2a138706ce60e":{
        "scriptId":"u12"},
      "e667355ff9d3481087a63a2969446b1f":{
        "scriptId":"u13"},
      "390cf107ac7d47c6bc44886f986313e5":{
        "scriptId":"u14"},
      "f8d846addf9d44219093509b900f40b3":{
        "scriptId":"u15"},
      "3a6132e387424d6fbbf2248b3654016c":{
        "scriptId":"u16"},
      "aba5fdd5f99240e3ab65e051386a96c5":{
        "scriptId":"u17"},
      "6889745b526b4678a3382c3ecc3ca560":{
        "scriptId":"u18"},
      "2bdce835ad7341c099f582ef7f5739a7":{
        "scriptId":"u19"},
      "604d913d8219424b904ea3538c9e709d":{
        "scriptId":"u20"},
      "0ab12be8507b4b5d96523b9689bef6d8":{
        "scriptId":"u21"},
      "5a09e75d78154126b36e9e911c560920":{
        "scriptId":"u22"},
      "bb7b3553b986493d94efa8d3936ba89e":{
        "scriptId":"u23"},
      "a14ef670f2004442bc29daa99eee55ba":{
        "scriptId":"u24"}},
    "ec4f40c8ea25448798f55ff492171af3":{
      "scriptId":"u25"},
    "9d21a472b3b04e02bc98399cfa38d373":{
      "scriptId":"u26"},
    "d82dd0e104d64c7c8e4eb0a8eeef7dce":{
      "scriptId":"u27"},
    "af9ee092195b45f082474bc8586eff9b":{
      "scriptId":"u28"},
    "f467c351e8df427cb2ece7a99d938ea1":{
      "scriptId":"u29"},
    "8f3afb451d934ce19a4688a28343379d":{
      "scriptId":"u30"},
    "a0251e17805842d08e330601ab4c2643":{
      "scriptId":"u31"},
    "da4ff92f00c0476daedc7347e18f2c57":{
      "scriptId":"u32"},
    "52034d29eb194f32b4be4cd82e5bc1ee":{
      "scriptId":"u33"},
    "cb5f4b0050b940b98f8f89ea252d1334":{
      "scriptId":"u34"},
    "db9ede3a09a1467c82d568a56ac6942c":{
      "scriptId":"u35"},
    "b5787e7dfdd04185b45edb5ba6b4d84e":{
      "scriptId":"u36"},
    "6090227c2de5406eb47239df0ff661a3":{
      "scriptId":"u37"},
    "d1b3cf4405174580a0fd4cdddf11e415":{
      "scriptId":"u38"},
    "94c78b94378843e7b1b127bd670c5e1a":{
      "scriptId":"u39"},
    "02ef2807bda94982972ba677cc39b1b9":{
      "scriptId":"u40"},
    "e3c867af4d0847fdbbc06c39c9661c40":{
      "scriptId":"u41"},
    "46cd8ff7193e49e4b291ffe07eda67cf":{
      "scriptId":"u42"},
    "f2a8ede4a4bd4587be6df333766540c8":{
      "scriptId":"u43"},
    "db901cb4e32d44b68f9f44f1a1ba8f1b":{
      "scriptId":"u44",
      "20f3cd74ae3948eb9611ff6704f923e8":{
        "scriptId":"u45"},
      "21b4e9ebc28c473dab39ebcb625bdf01":{
        "scriptId":"u46"}}}});